### ISSUE TITLE
PydanticUserError

### ISSUE THREAD

**Issue by Asif-droid** [LOGIC-10/RepoAgent#79]
After pip install repoagent 
running repoagent configure shows this error:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Scripts\repoagent.exe\__main__.py", line 4, in <module>
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\repo_agent\main.py", line 12, in <module>
    from repo_agent.chat_with_repo import main as run_chat_with_repo
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\repo_agent\chat_with_repo\__init__.py", line 3, in <module>  
    from .main import main
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\repo_agent\chat_with_repo\main.py", line 3, in <module>      
    from repo_agent.settings import setting
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\repo_agent\settings.py", line 27, in <module>
    class ProjectSettings(BaseSettings):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_model_construction.py", line 224, in __new__
    complete_model_class(
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_model_construction.py", line 577, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 671, in __get_pydantic_core_schema__ 
    return handler(source)
           ^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 924, in _generate_schema_inner
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 739, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1115, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1332, in _common_field_schema
    schema = self._apply_field_serializers(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 2221, in _apply_field_serializers
    is_field_serializer, info_arg = inspect_field_serializer(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\_internal\_decorators.py", line 586, in inspect_field_serializer
    raise PydanticUserError(
pydantic.errors.PydanticUserError: Unrecognized field_serializer function signature for <function ProjectSettings.serialize_ignore_list at 0x000001F8B665F4C0> with `mode=plain`:(self, ignore_list: list[str] = [])

For further information visit https://errors.pydantic.dev/2.9/u/field-serializer-signature

**Comment by a172166** [comment]
im also seeing this issue

**Comment by ElvaTheCoder** [comment]
Also having this issue, can anyone help to take a look at this?
